from pyramid.response import Response
from pyramid.view import view_config
from pyramid.security import NO_PERMISSION_REQUIRED,Authenticated
from ziggurat_foundations.ext.pyramid.sign_in import ZigguratSignInSuccess
from sqlalchemy.exc import DBAPIError
from ..models.models import Empleado
from ..models import MyModel
from ..models import get_session_callable
from ..models import ResourceFactory


class Vista(object):
    def __init__(self, request):
        print('HOLA:'+request.user.user_name)
       # emp=Empleado()
        print(request.authenticated_userid)
        #request.session.expunge('empleado')
        #emp=request.session['empleado']
        #empl=Empleado()
        #empl=emp
        #print(empl.NOMBRE)

    @view_config(route_name='home', renderer='../templates/mytemplate.jinja2', permission='edit')
    def my_view(request):


        #ResourceFactory(request)
        return {'one': 'one', 'project': 'sinvel'}




<<<<<<< HEAD
=======
@view_config(route_name='home', renderer='../templates/home.jinja2')
def my_view(request):
    try:
        query = request.dbsession.query(MyModel)
        one = query.filter(MyModel.name == 'one').first()
    except DBAPIError:
        return Response(db_err_msg, content_type='text/plain', status=500)
    return {'one': one, 'project': 'sinvel'}
>>>>>>> 16d124d8dae22c82c26730de715e2087a64ab930


db_err_msg = """\
Pyramid is having a problem using your SQL database.  The problem
might be caused by one of the following things:

1.  You may need to run the "initialize_sinvel_db" script
    to initialize your database tables.  Check your virtual
    environment's "bin" directory for this script and try to run it.

2.  Your database server may not be running.  Check that the
    database server referred to by the "sqlalchemy.url" setting in
    your "development.ini" file is running.

After you fix the problem, please restart the Pyramid application to
try it again.
"""
